/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liu_coordinate_NdkJniUtils */

#ifndef _Included_com_liu_coordinate_NdkJniUtils
#define _Included_com_liu_coordinate_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liu_coordinate_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liu_coordinate_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_liu_coordinate_NdkJniUtils
 * Method:    wgs2bd
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_liu_coordinate_NdkJniUtils_wgs2bd
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
