/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liu_testjni_NdkJniUtils */

#ifndef _Included_com_liu_testjni_NdkJniUtils
#define _Included_com_liu_testjni_NdkJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liu_testjni_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liu_testjni_NdkJniUtils_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_liu_testjni_NdkJniUtils
 * Method:    wgs2bd
 * Signature: ([Ljava/lang/Double;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_com_liu_testjni_NdkJniUtils_wgs2bd
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
